config/routes.rb
Rails.application.routes.draw do
  root "supports#index"
  get "/supports/search" => "supports#search", as: :supports_search
  resources :supports

end

app/models/support.rb
class Support < ActiveRecord::Base
  validates :name, presence: true
  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/supports_controller.rb
class SupportsController < ApplicationController
  before_action :find_support, only: [:show, :edit, :update, :destroy]

  def new
    @s = Support.new
  end

  def create
    @s = Support.new(support_params)
    if @s.save
      redirect_to(support_path(@s), notice: "Support created!")
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @s.update support_params
      redirect_to(support_path(@s))
    else
      render :edit
    end
  end

  def index
    #@supports = Support.all
    #@supports = Support.page(1).per(2)
    @supports = Support.page params[:page]
  end

  def destroy
    @s.destroy
    flash[:notice] = "Support deleted successfully"
    redirect_to supports_path
  end

  def search
    @search_string = params[:search][:search]
    @supports_name_length = Support.where("name ILIKE ?", "%#{@search_string}%").length
    @supports_email_length = Support.where("email ILIKE ?", "%#{@search_string}%").length
    @supports_message_length = Support.where("message ILIKE ?", "%#{@search_string}%").length

    @supports = Support.where("name ILIKE ? OR email ILIKE ? OR message ILIKE ?", "%#{@search_string}%", "%#{@search_string}%", "%#{@search_string}%").page params[:page]
    @supports_name = @supports.where("name ILIKE ?", "%#{@search_string}%")
    @supports_email = @supports.where("email ILIKE ?", "%#{@search_string}%")
    @supports_message = @supports.where("message ILIKE ?", "%#{@search_string}%")
  end

  private

  def support_params
    params.require(:support).permit([:name, :email, :department, :message, :done])
  end

  def find_support
    @s = Support.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/supports_helper.rb
module SupportsHelper
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="<%= root_path %>" ><i class='glyphicon glyphicon-home'></i> Home</a>
    </div>

<!-- Collect the nav links, forms, and other content for toggling -->
    <!-- <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li> <%#= link_to("<i class='glyphicon glyphicon-list-alt'></i> Posts".html_safe, posts_path) %></li>
        <li> <%#= link_to("<i class='glyphicon glyphicon-info-sign'></i> About".html_safe, about_path) %></li>
      </ul>
    </div> -->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Supporter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= render "/layouts/nav" %>

    <% if flash[:notice]%>
      <div class="alert alert-success"><%= flash[:notice] %></div>
    <% elsif flash[:alert]  %>
      <div class="alert alert-danger"><%= flash[:alert] %></div>
    <% end %>
    <%= yield %>
  </div>
</body>
</html>

app/views/supports/_form.html.erb
<%= @s.errors.full_messages.join(", ") %>
<%= form_for @s do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :email %>
    <%= f.email_field :email, class: "form-control" %>
  </div>
  <div class="form-group">
    <%#= f.radio_button :department, "Sales", class: "form-control" %>
    <%#= f.label :department, "Sales", :value => "Sales" %>
    <%#= f.radio_button :department, "Marketing", class: "form-control" %>
    <%#= f.label :department, "Marketing" %>
    <%#= f.radio_button :department, "Technical", class: "form-control" %>
    <%#= f.label :department, "Technical" %>
    <div class="row">
      <div class="col-lg-2">
       <div class="input-group">
         <span class="input-group-addon">
           <%= f.radio_button :department, "Sales" %>
         </span>
         <%= f.label :department, "Sales", class: "form-control" %>
       </div><!-- /input-group -->
     </div><!-- /.col-lg-6 -->
     <div class="col-lg-2">
      <div class="input-group">
        <span class="input-group-addon">
          <%= f.radio_button :department, "Marketing" %>
        </span>
        <%= f.label :department, "Marketing", class: "form-control" %>
      </div><!-- /input-group -->
    </div><!-- /.col-lg-6 -->
    <div class="col-lg-2">
     <div class="input-group">
       <span class="input-group-addon">
         <%= f.radio_button :department, "Technical" %>
       </span>
       <%= f.label :department, "Technical", class: "form-control" %>
     </div><!-- /input-group -->
   </div><!-- /.col-lg-6 -->
  </div>

  </div>
  <div class="form-group">
    <%= f.label :message %>
    <%= f.text_area :message, class: "form-control" %>
  </div>
  <div class="form-group">
    <%#= f.radio_button :done, true, class: "form-control" %>
    <%#= f.label :department, "Done", :value => true %>
    <%#= f.radio_button :done, false, :checked => true, class: "form-control" %>
    <%#= f.label :department, "Not Done", :value => false %>

    <div class="row">
      <div class="col-lg-2">
       <div class="input-group">
         <span class="input-group-addon">
           <%= f.radio_button :done, true %>
         </span>
         <%= f.label :department, "Done", :value => true,  class: "form-control" %>
       </div><!-- /input-group -->
     </div><!-- /.col-lg-6 -->
     <div class="col-lg-2">
      <div class="input-group">
        <span class="input-group-addon">
          <%= f.radio_button :done, false, :checked => true %>
        </span>
        <%= f.label :department, "Not Done", :value => false, class: "form-control" %>
      </div><!-- /input-group -->
    </div><!-- /.col-lg-6 -->
  </div>

  </div>
  <%= f.submit class: "btn btn-primary"%>
<% end %>

app/views/supports/edit.html.erb
<h1>Editing Supporter</h1>

<%= render "form" %>

app/views/supports/index.html.erb
<h1>All Supporters</h1>
<%= form_tag(:supports_search, method: "get") do %>
  <div class="form-group">
    <%= text_field :search, :search, class: "form-control" %>
    <%= submit_tag("Search", class: "btn btn-info") %>
    <%#= f.submit class: "btn btn-info"%>
  </div>
<% end %>
<div>
  <%= link_to("New Supporter", new_support_path, class: "btn btn-primary") %>
</div>
<div>
  <% done_supports = @supports.where(done: true) %>
  <% not_done_supports = @supports.where(done: false) %>
  <% not_done_supports.each do |s| %>
    <div class="well">
        <%= link_to s.name, support_path(s) %>
        <%= "Not Done" %>
    </div>
  <% end %>
  <% done_supports.each do |s| %>
    <div class="well">
        <%= link_to s.name, support_path(s) %>
        <%= "Done"%>
    </div>
  <% end %>
</div>
<%= paginate @supports %>

app/views/supports/new.html.erb
<h1>Create New Supporter</h1>

<%= render "form" %>

app/views/supports/search.html.erb
<h1>Search Results for <%= @search_string %></h1>
<p>Found <%= @supports_name_length %> results for name,
  <%= @supports_email_length %> results for email, and
  <%= @supports_message_length %> results for message</p>
<div>
  <% done_supports = @supports_name.where(done: true) %>
  <% not_done_supports = @supports_name.where(done: false) %>
  <% not_done_supports.each do |s| %>
    <div class="well">
        <%= link_to s.name, support_path(s) %>
        <%= "Not Done" %>
    </div>
  <% end %>
  <% done_supports.each do |s| %>
    <div class="well">
        <%= link_to s.name, support_path(s) %>
        <%= "Done"%>
    </div>
  <% end %>
</div>
<div>
  <% done_supports = @supports_email.where(done: true) %>
  <% not_done_supports = @supports_email.where(done: false) %>
  <% not_done_supports.each do |s| %>
    <div class="well">
        <%= link_to s.name, support_path(s) %>
        <a href="mailto:<%= s.email %>"><%= s.email %></a>
        <%= "Not Done" %>
    </div>
  <% end %>
  <% done_supports.each do |s| %>
    <div class="well">
        <%= link_to s.name, support_path(s) %>
        <a href="mailto:<%= s.email %>"><%= s.email %></a>
        <%= "Done"%>
    </div>
  <% end %>
</div>
<div>
  <% done_supports = @supports_message.where(done: true) %>
  <% not_done_supports = @supports_message.where(done: false) %>
  <% not_done_supports.each do |s| %>
    <div class="well">
        <%= link_to s.name, support_path(s) %>
        <%= s.message %>
        <%= "Not Done" %>
    </div>
  <% end %>
  <% done_supports.each do |s| %>
    <div class="well">
        <%= link_to s.name, support_path(s) %>
        <%= s.message %>
        <%= "Done"%>
    </div>
  <% end %>
</div>
<%= paginate @supports %>

app/views/supports/show.html.erb
<h1><%= @s.name %></h1>
<a href="mailto:<%= @s.email %>"><%= @s.email %></a>
<p><%= @s.department %></p>
<p><%= @s.message %></p>
<p><%= @s.done ? "Done" : "Not Done" %></p>


<%= link_to "Edit", edit_support_path(@s), class: "btn btn-info btn-sm" %>
<%= link_to "Delete", support_path(@s), {method: :delete, class: "btn btn-danger btn-sm", data: {confirm: "Are you sure you want to delete this support?"}}%>